### ISSUE TITLE
Error: No formulae or casks found for "lookaway"

### ISSUE THREAD

**Issue by jimsmith** [mysticalbits/lookaway-releases#1]
```
$ brew search lookaway
Error: No formulae or casks found for "lookaway".

$ brew search --cask lookaway
Error: No formulae or casks found for "lookaway".

$ brew install --cask lookaway
Warning: Cask 'lookaway' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
Error: No casks found for lookaway.

```

**Comment by jimsmith** [comment]
transient issue, resolved itself now installed.

**Comment by kushsolitary** [comment]
Hi @jimsmith,

Is your brew up-to-date? It should show the following output:

`$ brew search lookaway`
```bash
==> Casks
lookaway ✔
```

`$ brew info lookaway`
```bash
==> lookaway: 1.4.5 (auto_updates)
https://lookaway.app/
/usr/local/Caskroom/lookaway/1.4.2 (122B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/l/lookaway.rb
==> Name
LookAway
==> Description
Break time reminder app
==> Artifacts
LookAway.app (App)
==> Analytics
install: 87 (30 days), 87 (90 days), 87 (365 days)
```

Here's what you can try if it still persists - https://stackoverflow.com/questions/41113448/homebrew-error-no-formulae-found-in-taps

**Comment by jimsmith** [comment]
Hi @kushsolitary yes it's up to date, it's now installed 👍🏻
```
 $ brew install --cask lookaway
==> Downloading https://github.com/mysticalbits/lookaway-releases/releases/download/1.4.5/LookAway.dmg
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/a86651cd223203985b4b13a2d868a444b8dce0a6baec1fbfb6a87a9d7e34dda1--LookAway.dmg
==> Installing Cask lookaway
==> Moving App 'LookAway.app' to '/Applications/LookAway.app'
🍺  lookaway was successfully installed!
```

**Comment by kushsolitary** [comment]
Perfect - let me know if you face any issues!

**Comment by jimsmith** [comment]
The only issue so far after initially launching the app is changing the settings as when opening up `LookAway.app` nothing happens.

Mac OS: Apple M2 Max, Sonoma 14.4.1

**Comment by kushsolitary** [comment]
Hmm that's weird. You should see an onboarding which lets you set the focus and break times. Plus you should also see it in the menu bar from where you can open the detailed settings. Does the onboarding not show up for you on opening the app?

**Comment by jimsmith** [comment]
Yes I got the onboarding after launching it the first time for focus and break times, I can see LookAway running with Activity Monitor also.

One thing I do notice is that when you mention menu bar there isn't anything showing up.

![image](https://github.com/mysticalbits/lookaway-releases/assets/2676701/f4693f92-1a7a-409e-ac24-e70b6d70439e)


Mac OS: Apple M2 Max, Sonoma 14.4.1

**Comment by kushsolitary** [comment]
Seems like your mac is hiding the icon because there's a lack of space. See here for more info: https://apple.stackexchange.com/questions/444113/how-to-prevent-macbook-pro-notch-from-hiding-menu-bar-icons-from-the-right

I would recommend either hiding some of the existing ones which you don't use or using an app like Bartender to manage the icons.

**Comment by jimsmith** [comment]
<img width="259" alt="image" src="https://github.com/mysticalbits/lookaway-releases/assets/2676701/f16a04b5-942c-43ce-8908-14528fc896b6">

😻

Awesome thanks very much @kushsolitary

**Comment by kushsolitary** [comment]
wohoo!
